import type { Metadata } from "next";
import "../style/globals.css";
import Header from "@/components/ui/Header";
import { Toaster } from "@/components/ui/sonner"

export const metadata: Metadata = {
  title: "Technical Interview",
  description: "Generated by Webstrail",
  icons: {
    icon: "/globe.svg",
    shortcut: "/globe.svg",
    apple: "/globe.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-screen flex flex-col">
        <Header />
        <Toaster position="top-center" /> 
        <main className="flex-1 overflow-auto min-h-0">
          
          <div className="container mx-auto p-4">{children}</div>
        </main>
      </body>
    </html>
  );
}
